LoggingLevels:
  #Levels:
    #NONE = absolutely no info
    #ERROR = print colorful message in addition to errors stacktrace
    #WARNING = ERRORS + warnings info
    #FULL = print complex info about setup (default both for setup and runtime)
    #DEBUG = print too many info
  LoggerSetup: FULL
  LoggerRuntime: FULL

Database:
  Connection:
    IP: localhost
    Database: MaRPG
    Username: Marcoral
    Password: obfuscated
  
  Setup:
    MaximumPoolSize: 10
    DataSourceProperties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048

Worlds:
  Defaults:
    Gamerules:
      doFireTick: false
      doMobLoot: false
      mobGriefing: false
      doMobSpawning: false
      doWeatherCycle: false
      showDeathMessages: false
      naturalRegeneration: false
      keepInventory: true
      reducedDebugInfo: true
      doLimitedCrafting: true
      randomTickSpeed: 0 
  Specified:
    Karhan:
      # Minecraft world directory name
      Name: "Karhan"