LoggingLevels:
  #Levels:
    #NONE = absolutely no info
    #ERROR = print colorful message in addition to errors stacktrace
    #WARNING = ERRORS + warnings info
    #FULL = print complex info about setup (default both for setup and runtime)
    #DEBUG = print too many info
  LoggerSetup: FULL
  LoggerRuntime: FULL

Connection:
  IP: localhost
  Port: 3306
  Database: MaRPG
  Username: Marcoral
  Password: obfuscated

Worlds:
  Defaults:
    Gamerules:
      doFireTick: false
      doMobLoot: false
      mobGriefing: false
      doMobSpawning: false
      doWeatherCycle: false
      showDeathMessages: false
      naturalRegeneration: false
      keepInventory: true
      reducedDebugInfo: true
      doLimitedCrafting: true
      randomTickSpeed: 0 
  Specified:
    Karhan:
      # Minecraft world directory name
      Name: "Karhan"