package pl.mateam.marpg.api.submodules.text;

public enum TextNode {
	LOGIN_GAMEMASTER_IMPERSONATE("LOGIN_GAMEMASTER-IMPERSONATE"), 
	LOGIN_DATABASE_NOT_SETUP("LOGIN_DATABASE-NOT-SETUP"),
	
	FORMAT_BANNED_MESSAGE_TEMPLATE("FORMAT_BANNED-MESSAGE-TEMPLATE"),
	FORMAT_BANNED_MESSAGE_WHOBANNED("FORMAT_BANNED-MESSAGE-WHOBANNED"),
	FORMAT_BANNED_MESSAGE_EXPIRES("FORMAT_BANNED-MESSAGE-EXPIRES"),
	FORMAT_BANNED_MESSAGE_BAR_PERCENTS("FORMAT_BANNED-MESSAGE-BAR-PERCENTS");
	
	private final String path;
	private TextNode(String path) {
		this.path = path;
	}
	
	public String getPath() {
		return path;
	}
}
